"
" popkirby's vimrc
" ====================================================================== 


" Initialize
" ----------------------------------------------------------------------

" source script from rc directory.
function! s:source_rc(path)
  execute 'source' fnameescape(expand('$DOTFILES/vim/rc/' . a:path))
endfunction

call s:source_rc('init.vim')

call neobundle#begin()

if neobundle#load_cache()
  NeoBundleFetch 'Shougo/neobundle.vim'

  NeoBundle 'Shougo/vimproc.vim', {
        \ 'build' : {
        \   'mac' : 'make -f make_mac.mak',
        \   'unix' : 'make -f make_unix.mak'
        \ }}

  " load bundle settings from toml file
  call neobundle#load_toml(expand('$DOTFILES/vim/rc/neobundle.toml'), {'lazy' : 1})

  NeoBundleSaveCache
endif


" load plugin settings.
call s:source_rc('plugins.vim')

call neobundle#end()

filetype plugin indent on
syntax enable

if !has('vim_starting')
  " check plugin installation.
  NeoBundleCheck
endif


" Encoding
" ----------------------------------------------------------------------

call s:source_rc('encoding.vim')


" Edit
" ----------------------------------------------------------------------

call s:source_rc('edit.vim')


" View
" ----------------------------------------------------------------------

call s:source_rc('view.vim')


" Filetype
" ----------------------------------------------------------------------

call s:source_rc('filetype.vim')


" Mappings
" ----------------------------------------------------------------------

call s:source_rc('mappings.vim')

" Commands
" ----------------------------------------------------------------------

call s:source_rc('commands.vim')


" Others
" ----------------------------------------------------------------------

if has('nvim')
  call s:source_rc('nvim.vim')
endif

if executable('zsh')
  set shell=zsh
endif

set secure

