# dotmgr config
install:
  link:
    - src: .zshenv
      dst: ~/.zshenv
  exec:
    - "[[ ! -d '.zprezto' ]] && git clone --recursive https://github.com/sorin-ionescu/prezto .zprezto"
update:
  exec:
    - cd .zprezto && git pull && git submodule update --init --recursive
